version: '3.4'

services:
    catalogdb:
        image: mongo
    basketdb:
       image: redis
    rabbitmq:
       image: rabbitmq:3-management
        
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Catalog.Api/Dockerfile
    
    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Basket.Api/Dockerfile
    
    